### ISSUE TITLE
I created something similar

### ISSUE THREAD

**Issue by ntninja** [hyperair/flake8-expandtab#1]
Hi! I found your plugin a couple of weeks ago and decided yesterday that I'm going to reimplement it “properly”, so here it is: https://pypi.org/project/flake8-tabs/
The main difference is that this plugin actually checks whether the given code complies with the “tabs for indentation, tabs for alignment”, as well as checking whether indentation (using this scheme) was done proper.
I thought maybe this may be interesting to you or your users. :slightly_smiling_face:

**Comment by hyperair** [comment]
Hi @alexander255. This does sound very interesting, but there isn't really anything worth doing for `flake8-expandtab` in the context of this issue, so I'm closing it. I think you can continue to leave comments on a closed issue so feel free to continue the discussion.

Overall I feel that there are pros and cons of both approaches. `flake8-tabs` is cleaner and definitely helps lint code using smart-tabs better, but I think `flake8-expandtabs` is likely to be more future-proof with minimal effort if/when flake8 or other third-party plugins add more checks that are affected by indentation. It's probably worth having both packages floating around the PyPI and letting users pick whichever tool suits their purposes better.

**Comment by ntninja** [comment]
@hyperair: I fully agree with everything you said. Just wanted to put this here as it somehow felt relevant.

Cheers!
